### ISSUE TITLE
Нужно название для бота

### ISSUE THREAD

**Issue by e-gress** [msu-students-union/telegram-bot#1]
Нужно придумать название для бота:
1) name, которое может быть любое.
2) username, которое должно быть свободно, заканчиваться на bot и быть запоминающимся, так как будет использоваться в ссылках: telegram.me/username

**Comment by DarthKitsune** [comment]
1) Name - MSU_TB_bot
2) username - см. 1)

**Comment by e-gress** [comment]
Name можно хороший сделать "MSU Бот", "Студенческий бот", "Стубот" и т д.

**Comment by e-gress** [comment]
Пока используем тестового бота
