### ISSUE TITLE
Ознакомиться с api и составить задачи на 0 итерацию.

### ISSUE THREAD

**Issue by e-gress** [msu-students-union/telegram-bot#2]
Нужно ознакомиться с bot API https://core.telegram.org/bots/api и с созданием бота https://core.telegram.org/bots и расписать задачи на нулевую итерацию. После чего поставить ограничение на число одновременно разрабатываемых задач и примерные сроки конца итерации.

**Comment by DarthKitsune** [comment]
Задачи:
1) Скачать "ядро" бота
2) Зарегать бота в фазере
3) Настроить бота под полученные ключи
4) Заставить его эхом повторять фразы

Пример (подробнее) : http://habrahabr.ru/post/262247/

**Comment by e-gress** [comment]
1) Ядра бота нет. API - обычный rest api, хоть с консоли запросы шли.

**Comment by DarthKitsune** [comment]
1) Можно реализовать базовую версию, пользуясь статейкой. А после расширить

**Comment by e-gress** [comment]
1) Да там все в целом очевидненько)
